#!/usr/bin/env python3

import sys
import os
import KoocFile
from Knodes import k_to_c

# get entry filename

koocFileName = sys.argv[1]
fileName, fileExtension = os.path.splitext(koocFileName)
try:
	KoocFile.includePath = os.path.dirname(os.path.abspath(koocFileName))
except Exception:
	print("fail tu cut path")
	pass

# out file creation

if fileExtension == ".kc":
    fout = open(fileName + ".c", "w")
elif fileExtension == ".kh":
    fout = open(fileName + ".h", "w")
else:
    print("Kooc Error : Unknow file extension")
    exit()

# kooc !

ast = KoocFile.kooc_a_file(koocFileName)

# to_c call

result = str(k_to_c.k_to_c(ast))

# writing result

fout.write(result)
fout.close()
