#!/usr/bin/env python3

import sys
import os
from Exceptions.KoocException import KoocException

# TODO : a retirer dans la version finale !
sys.tracebacklimit = 0

try:
    import KoocFile
    from knodes import to_c
except KeyboardInterrupt:
    print("")
    sys.exit(0)

if len(sys.argv) != 2:
    print("./kooc [file.kc | file.kh]")
    sys.exit(0)

# get entry filename
koocFileName = sys.argv[1]
fileName, fileExtension = os.path.splitext(koocFileName)
try:
	KoocFile.includePath = os.path.dirname(os.path.abspath(koocFileName))
except Exception:
	print("fail tu cut path")
	pass

# out file creation

if fileExtension == ".kc":
    fout = open(fileName + ".c", "w")
elif fileExtension == ".kh":
    fout = open(fileName + ".h", "w")
else:
    print("Kooc Error : Unknow file extension")
    exit()

# kooc !

try:
    ast = KoocFile.kooc_a_file(koocFileName)

    # to_c call
    
    try:
        result = str(to_c.k_to_c(ast))
        # writing result
        fout.write(result)
    except AttributeError as e:
        print("Error on parsing: ", e)
        print(ast.diagnostic.get_content())
    
    fout.close()

except RuntimeError as e:#TODO : catcher KoocException quand elle sera bien envoyée
    print(e)
except KoocException as e:#TODO : catcher KoocException quand elle sera bien envoyée
    print(e)
